stages:
  - unit-test
  - robot-test
  - deploy


test_unitarios:
  stage: unit-test
  image: maven:3.9.4-eclipse-temurin-21 
  script:
    - cd backend/springboot
    - mvn test 

robot:
  image: python:3.11.4
  stage: robot-test
  before_script:
    - apt-get update -qq -y
    - apt-get install -y wget unzip fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0
      libcups2 libdbus-1-3 libdrm2 libgbm1 libgtk-4-1 libnspr4 libnss3 libu2f-udev libvulkan1 libxcomposite1
      libxdamage1 libxfixes3 libxkbcommon0 libxrandr2 xdg-utils xvfb
    # Instalar Firefox
    - apt-get install -y firefox-esr
    # Baixar e configurar Geckodriver
    - wget -q -O geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz
    - tar -xvzf geckodriver.tar.gz
    - chmod +x geckodriver
    - mv geckodriver /usr/local/bin/
    # Verificar versões
    - firefox --version
    - geckodriver --version
    # Instalar dependências Python
    - pip3 install selenium robotframework robotframework-seleniumlibrary
  script:
    # - xvfb-run -a robot --variable HEADLESS_OPTIONS:"--headless" ./tests/test.robot
    - xvfb-run -a robot --variable HEADLESS_OPTIONS:"--headless" ./tests/usersTest.robot
    # - xvfb-run -a robot --variable HEADLESS_OPTIONS:"--headless" ./tests/rentersTest.robot
    # - xvfb-run -a robot --variable HEADLESS_OPTIONS:"--headless" ./tests/publishersTest.robot
    # - xvfb-run -a robot --variable HEADLESS_OPTIONS:"--headless" ./tests/booksTest.robot
    # - xvfb-run -a robot --variable HEADLESS_OPTIONS:"--headless" ./tests/rentsTest.robot
    
.deploy :
  stage : deploy
  script :
    - >
      sudo --preserve-env
      docker-compose
      --project-name "livraria-ryan-$CI_COMMIT_REF_SLUG"
      up -d --build

deploy_develop :
  extends : .deploy
  environment : develop
  only :
    - develop
  tags :
    - runner_dev
